spring.application.name=ECommerceApp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=Sanchita@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


paypal.client.id=Af3_FIQMgVzxr5QPKPcqYaLUBMqMUt3HvAKy8AQr1vNc19xZaPWNBNlkmz-R8imM2Wv-XtlOniK9v2gb
paypal.client.secret=ENoXhW-MiDIlIwDh6Hpxb4goug9plrdhNveaNL1o7qsntZObPvaCCQYKVsvrpcvHh_fNE2zbOxfQYEXS
paypal.mode=sandbox

jwt.secret=Xq2x4lI6vEw9zJX8s9wU1Q0FZ7c2L3Xr9qYz0aR7BQs=
jwt.expiration=86400000
